name: CI Starter Guide

on:
  push:
    branches: [ "main" ]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Test running script
        run: echo "GitHub Actions is working successfully!"
